jQuery.sap.registerPreloadedModules({
	"version": "2.0",
	"name": "dist/WebContent/Component-preload",
	"modules": {
		"WebContent/Component.js": "sap.ui.define([\"sap/ui/core/UIComponent\"],function(t){\"use strict\";return t.extend(\"DemoEmp.Component\",{metadata:{manifest:\"json\"},init:function(){t.prototype.init.apply(this,arguments),this.getRouter().initialize()}})});",
		"WebContent/controller/App.controller.js": "sap.ui.define([\"DemoEmp/controller/BaseController\"],function(e){\"use strict\";return e.extend(\"DemoEmp.controller.App\",{})});",
		"WebContent/controller/BaseController.js": "sap.ui.define([\"sap/ui/core/mvc/Controller\",\"sap/ui/core/routing/History\"],function(e,o){\"use strict\";return e.extend(\"DemoEmp.controller.BaseController\",{getRouter:function(){return sap.ui.core.UIComponent.getRouterFor(this)},getModel:function(e){return this.getView().getModel(e)},onNavBack:function(e){var t,r;t=o.getInstance(),r=t.getPreviousHash(),void 0!==r?window.history.go(-1):this.getRouter().navTo(\"appHome\",{},!0)}})});",
		"WebContent/controller/Create.controller.js": "",
		"WebContent/controller/EmpDet.controller.js": "sap.ui.define([\"DemoEmp/controller/BaseController\"],function(t){\"use strict\";return t.extend(\"DemoEmp.controller.EmpDet\",{onInit:function(){this.getRouter().getRoute(\"EmpDet\").attachPatternMatched(this._onObjectMatched,this)},_onObjectMatched:function(t){var e=t.getParameter(\"arguments\").empId;this.getModel().metadataLoaded().then(function(){var t=this.getModel().createKey(\"ET_EMP_LISTSet\",{Empno:e});this._bindView(\"/\"+t)}.bind(this))},_bindView:function(t){var e=this.getModel();this.getView().bindElement({path:t,events:{change:this._onBindingChange.bind(this),dataRequested:function(t){e.metadataLoaded.then(function(){})},dataReceived:function(t){}}})},_onBindingChange:function(t){}})});",
		"WebContent/controller/EmpList.controller.js": "sap.ui.define([\"DemoEmp/controller/BaseController\"],function(t){\"use strict\";return t.extend(\"DemoEmp.controller.EmpList\",{onInit:function(){},onPress:function(t){this._showDetail(t.getSource())},_showDetail:function(t){this.getRouter().navTo(\"EmpDet\",{empId:t.getBindingContext().getProperty(\"Empno\")})}})});",
		"WebContent/view/App.view.xml": "<mvc:View\r\n\txmlns:mvc=\"sap.ui.core.mvc\"\r\n\tcontrollerName=\"DemoEmp.controller.App\"\r\n\tdisplayBlock=\"true\"\r\n\txmlns=\"sap.m\"><App id=\"RootView\"></App></mvc:View>",
		"WebContent/view/Create.view.xml": "",
		"WebContent/view/EmpDet.view.xml": "<mvc:View controllerName=\"DemoEmp.controller.EmpDet\" xmlns=\"sap.m\" xmlns:mvc=\"sap.ui.core.mvc\"\r\n\txmlns:form=\"sap.ui.layout.form\"><Panel class=\"sapUiResponsiveMargin\" width=\"auto\" headerText=\"Employee Details\" expandable=\"true\" expanded=\"true\"><content><form:SimpleForm id=\"objectForm\"><form:content><Label id=\"EmpNoLbl\" text=\"Employee No.\"/><Text id=\"EmpNo\" text=\"{Empno}\"/><Label text=\"Name\"/><Text text=\"{Name}\"/><Label text=\"DOB\"/><Text text=\"{Dob}\"/><Label text=\"Address\"/><Text text=\"{Addr}\"/><Label text=\"Mobile\"/><Text text=\"{Mob}\"/></form:content></form:SimpleForm></content></Panel></mvc:View>",
		"WebContent/view/EmpList.view.xml": "<mvc:View controllerName=\"DemoEmp.controller.EmpList\"\r\n\txmlns:mvc=\"sap.ui.core.mvc\" xmlns=\"sap.m\"><Page title=\"Employee List\"><Table id=\"idProductsTable\" inset=\"false\" width=\"auto\"\r\n\t\titems=\"{path: '/ET_EMP_LISTSet'}\"><headerToolbar><Toolbar><Title text=\"Products\" level=\"H2\" /></Toolbar></headerToolbar><columns><Column width=\"12em\"><Text text=\"Employee No.\" /></Column><Column minScreenWidth=\"Tablet\" demandPopin=\"true\"><Text text=\"Name\" /></Column><Column minScreenWidth=\"Tablet\" demandPopin=\"true\" hAlign=\"End\"><Text text=\"DOB\" /></Column><Column minScreenWidth=\"Tablet\" demandPopin=\"true\" hAlign=\"Center\"><Text text=\"Address\" /></Column><Column hAlign=\"End\"><Text text=\"Mobile\" /></Column></columns><items><ColumnListItem type=\"Navigation\" press=\"onPress\"><cells><ObjectIdentifier text=\"{Empno}\" /><Text text=\"{Name}\" /><Text text=\"{Dob}\" /><Text text=\"{Addr}\" /><Text text=\"{Mob}\" /></cells></ColumnListItem></items></Table></Page></mvc:View>",
		"WebContent/manifest.json": "{\"_version\":\"1.2.0\",\"sap.app\":{\"_version\":\"1.2.0\",\"id\":\"DemoEmp\",\"type\":\"application\",\"i18n\":\"i18n/i18n.properties\",\"title\":\"{{appTitle}}\",\"description\":\"{{appDescription}}\",\"applicationVersion\":{\"version\":\"1.0.0\"},\"dataSources\":{\"mainservice\":{\"uri\":\"proxy/sap/opu/odata/sap/ZDEMO_01_SRV/\",\"type\":\"OData\",\"settings\":{\"odataVersion\":\"2.0\",\"localUri\":\"localService/metadata.xml\"}}}},\"sap.ui\":{\"_version\":\"1.2.0\",\"technology\":\"UI5\",\"icons\":{\"icon\":\"sap-icon://task\",\"favIcon\":\"\",\"phone\":\"\",\"phone@2\":\"\",\"tablet\":\"\",\"tablet@2\":\"\"},\"deviceTypes\":{\"desktop\":true,\"tablet\":true,\"phone\":true},\"supportedThemes\":[\"sap_hcb\",\"sap_bluecrystal\"]},\"sap.ui5\":{\"_version\":\"1.2.0\",\"rootView\":{\"viewName\":\"DemoEmp.view.App\",\"type\":\"XML\",\"id\":\"RootView\"},\"dependencies\":{\"minUI5Version\":\"1.36.0\",\"libs\":{\"sap.ui.core\":{\"minVersion\":\"1.36.0\"},\"sap.m\":{\"minVersion\":\"1.36.0\"}}},\"contentDensities\":{\"compact\":true,\"cozy\":true},\"models\":{\"i18n\":{\"type\":\"sap.ui.model.resource.ResourceModel\",\"settings\":{\"bundleName\":\"DemoEmp.i18n.i18n\"}},\"\":{\"dataSource\":\"mainservice\",\"settings\":{\"defaultBindingMode\":\"TwoWay\",\"metadataUrlParams\":{\"sap-documentation\":\"heading\"},\"useBatch\":false}}},\"resources\":{\"css\":[{\"uri\":\"CSS/style.css\"}]},\"routing\":{\"config\":{\"routerClass\":\"sap.m.routing.Router\",\"viewType\":\"XML\",\"viewPath\":\"DemoEmp.view\",\"controlId\":\"RootView\",\"controlAggregation\":\"pages\",\"transition\":\"slide\",\"bypassed\":{\"target\":[\"notFound\"]},\"async\":true},\"routes\":[{\"pattern\":\"\",\"name\":\"Main\",\"target\":[\"Main\"]},{\"pattern\":\"EmpDet/{empId}\",\"name\":\"EmpDet\",\"target\":[\"EmpDet\"]}],\"targets\":{\"Main\":{\"viewName\":\"EmpList\",\"viewId\":\"EmpList\",\"viewLevel\":1},\"EmpDet\":{\"viewName\":\"EmpDet\",\"viewId\":\"EmpDet\",\"viewLevel\":2},\"objectNotFound\":{\"viewName\":\"ObjectNotFound\",\"viewId\":\"objectNotFound\"},\"notFound\":{\"viewName\":\"ObjectNotFound\",\"viewId\":\"notFound\"}}}},\"sap.platform.hcp\":{\"uri\":\"webapp\",\"_version\":\"1.1.0\"}}"
	}
});